### ISSUE TITLE
Is tags.json deprecated

### ISSUE THREAD

**Issue by MaceChettiyadan** [GrimReaper2654/WACE-Database#10]
Is it used at all?

**Comment by GrimReaper2654** [comment]
it is not used if tagsV2 has all the subjects

**Comment by GrimReaper2654** [comment]
has econs been added to tagsV2 yet? If so, you can delete it

**Comment by GrimReaper2654** [comment]
tags.json is now deprecated and has been removed

**Comment by RJDJcool3** [comment]
Is tagsV2 going to be renamed to tags now that the original file is gone?
