### ISSUE TITLE
Recommendations for new tags

### ISSUE THREAD

**Issue by MaceChettiyadan** [GrimReaper2654/WACE-Database#12]
These will be difficult to add (especially to pre-existing questions) so not entirely required but:
1. Locuses (locii) of complex numbers
2. Simple Harmonic Motion
3. Logistic Equation

all for spec

**Comment by MaceChettiyadan** [comment]
actually maybe for logistic, differential equations instead - not entirely sure.

**Comment by GrimReaper2654** [comment]
go for it, those are pretty good tags, just didn't come up in any of the exams I've tagged

**Comment by GrimReaper2654** [comment]
somebody go through all the questions and add them pls
