### ISSUE TITLE
Discord invite in README.md is outdated

### ISSUE THREAD

**Issue by Midnightific** [GrimReaper2654/WACE-Database#120]
**Describe the bug**
Title.

**To Reproduce**
1. Open/view [README.md](https://github.com/GrimReaper2654/WACE-Database/blob/main/README.md)
2. Attempt to join the discord
3. Fails as the invite is outdated

**Expected behavior**
User should be able to join the discord server.

**Screenshots**
![CleanShot 2024-11-09 at 22 05 00@2x](https://github.com/user-attachments/assets/e6d3870b-3f6a-41cd-8d7d-3343ad7f8ef6)

**Additional context**
Would advise using the discord link on the website as that's up to date and for consistency as well.

**Comment by tvdk-sudoku** [comment]
I have updated the link. Hopefully this one shouldn't expire
