### ISSUE TITLE
Add Off Course Tag for Econs Questions

### ISSUE THREAD

**Issue by GrimReaper2654** [GrimReaper2654/WACE-Database#21]
I think it would be a good idea personally.

**Comment by RJDJcool3** [comment]
Btw Tom could you add me as a collaborator please?

**Comment by GrimReaper2654** [comment]
I added u

**Comment by GrimReaper2654** [comment]
I have added the tag. Can you tag all the off course questions for econs thanks

**Comment by RJDJcool3** [comment]
Still need to double check the structural change question (Q31) in 2023 WACE is part of the course. I couldn't find any information about it, but I'm not 100% sure it was removed, so I'll need to double check with Mr Paranchody before I tag it. Thus I'm leaving this issue open for now.

**Comment by RJDJcool3** [comment]
Checked with Mr P, structural change is off the course. I've tagged the question. If anyone has better names for the 'Removed from Course' tag let me know, clarity is the most important aspect.
