### ISSUE TITLE
Specialist Tags Missing/Disorganised

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#27]
The categories for the Specialist tags don't fully encapsulate the course, it would be much better to add:
- Implicit Differentiation
- Trigonometric Integration
- Partial Fractions
- Logistic Model

and remove the overarching differentiation/integration tags

This would require retagging of 2023, 2022 and 2021 calc free
I am willing to retag these exams if the tag changes are made

I also think we don't need so many sub-tags, SHM can be its own tag, trigonometry doesn't appear as a topic, but rather only through other topics (e.g. trigonometric integration) and could be removed. Vectors should have a Vector Calculus tag and instead of planes and spheres, a 3D Vectors tag encapsulates both of those questions types. I don't think spheres are prevalent enough on their own to warrant a tag, but I think this is debatable.

---

I think this could also be somewhat done for Methods before we start tagging lots of questions (for Methods, I think it would be best to have Chain Rule, Quotient Rule, etc. sub-tags)

**Comment by RJDJcool3** [comment]
I would like to hear others thoughts before working on anything

**Comment by GrimReaper2654** [comment]
I think most of that could work. I still feel like having diff and integration are kinda relevant tho

**Comment by RJDJcool3** [comment]
I have also reconsidered, I think it is important to break calculus up into the two branches. But I would do it by instead of having a 'Calculus' tag, to just have a differentiation and antidifferentiation tag. In my opinion, I think that would be the best option, especially since there is no overarching 'Calculus' topic in Specialist (in name).

**Comment by RJDJcool3** [comment]
Specialist Tags have been redone, people can have a look and start retagging the Spec papers now

**Comment by RJDJcool3** [comment]
I'm going to also have a look at the Methods tags, which means everything from above applies to Methods as well

**Comment by RJDJcool3** [comment]
Specialist 2023 has been re-tagged, 2022 and 2021 Calc Free left to do
Methods has been re-tagged as well btw

**Comment by RJDJcool3** [comment]
Only 2017 left to re-tag, I may move on to just general tagging for Spec until I reach 2017

**Comment by GrimReaper2654** [comment]
This is basically fixed, probs don't need the issue anymore
