### ISSUE TITLE
Change Tags Based on Selected Subject

### ISSUE THREAD

**Issue by tvdk-sudoku** [GrimReaper2654/WACE-Database#3]
So you don't have the spec tags taking up space when you want Chemistry questions

![image](https://github.com/user-attachments/assets/bc357014-c5c8-4293-96cb-174c9b033200)

**Comment by GrimReaper2654** [comment]
other subjects don't have tags set to the code breaks and tags don't change lmao

**Comment by GrimReaper2654** [comment]
should work now
