### ISSUE TITLE
Tag Groups Difficult to Use/Very Messy

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#33]
For several subjects, we have ended having massive groupings of tags which have been necessary to capture key parts of the course. Rather than trying to split up into lots of sub-groups, which will be confusing and messy, is there a way to change how the tag dropdown menu looks/how the elements fit on the page so that using tags on the website is easier?

We want to avoid this: 

![image](https://github.com/user-attachments/assets/4b6e38a1-dadd-4cee-a41f-b347f2ecbb77)

I've gotten feedback from other users complaining about this.

**Comment by GrimReaper2654** [comment]
I wanted to avoid fixing this for as long as possible since it would take quite a bit of effort. I'll have to investigate masonry.js or something similar and try get it working tomorrow.

**Comment by GrimReaper2654** [comment]
fixed
