### ISSUE TITLE
Clicking Search Clears Your Selected Tags

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#41]
This is not user friendly. Say you want to add/remove a tag from your list of tags, or switch the query from OR to AND, if you already pressed search you have to re-input tags which is currently not great because of the bad UI. Is there a way to not clear your tag selections upon clicking search?

**Comment by GrimReaper2654** [comment]
This is a bug introduced by my latest update. I had a feeling something would break...
Anyways, I do plan on fixing it, as well as adding a clear all tags button.

**Comment by GrimReaper2654** [comment]
fixed
