### ISSUE TITLE
Tag Groups Closing After Clicking On Question

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#47]
![image](https://github.com/user-attachments/assets/5617b4bb-cdcf-499e-bc16-9f88aeb98016)

Can it be changed so that tag groups remain open even when you click on a question? Makes it easier to change what tags you have applied later on.

**Comment by GrimReaper2654** [comment]
fixed

**Comment by RJDJcool3** [comment]
Nice
