### ISSUE TITLE
Add User Feedback

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#57]
Add a page where users can submit feedback,
e.g. missing tag/tag suggestion/missing question or marking key

**Comment by RJDJcool3** [comment]
This will be a crucial feature when the website starts being used more often as we will need a way to maintain it and resolve any errors which will definitely still be around.

**Comment by GrimReaper2654** [comment]
I can try to make something, but that would require the user to have a github account and token. Otherwise, I would have to set up a firebase server. Or I could simply add a link to the issues page of the repo and make it as simple as possible to create an issue.

**Comment by GrimReaper2654** [comment]
added
