### ISSUE TITLE
Duplicating Database Tab Resets Page but Doesn't Reset Selected Subject

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#58]
This may be just a very minor issue, but lets say you are looking at Methods papers and you want to duplicate your tag to open a different set of Methods papers, the new tab looks like this:

![image](https://github.com/user-attachments/assets/21bd9113-0664-404f-8bc8-fbaed4095256)

See anything off? The website treats it like you have Spec open and normally this isn't really a big deal, but:
To start searching for Methods papers, you need to switch to another subject and then back to Methods which is not user friendly.

This issue only happens when duplicating a tab, not from reloading the page. If this is a small fix, it would be well worth it but this is a negligible issue, just thought it was best to share since it has been a recurring minor annoyance.

**Comment by GrimReaper2654** [comment]
this is kinda weird ngl. Duplicating tab is handled by the browser and is out of my control. The best thing I can think of is acutally implementing saving search settings to localstorage, but that would only make it consistent across tabs. Perhaps I could find a way to track which tab it is and save that to localstorage as well but idk how to do that. Or I could store search settings in the url, which I don't really want to do. What do you think?

**Comment by GrimReaper2654** [comment]
Actually, nevermind that. There is a rather simple solution. If I check the inputs after the page fully loads, it should be able to recognise it correctly.
