### ISSUE TITLE
Switching to 'Database' page, duplicating tag or reloading page sets default subject to Methods

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#67]
This happens regardless of the last selected subject.  Methods is shown as the chosen subject regardless of the tags below.

e.g. just simply clicking the database button selects Methods as the subject, but the Specialist tags are shown (as they should as Spec is the default/first subject)

![image](https://github.com/user-attachments/assets/bcd6811e-e681-4f8a-ae2c-39c499b86161)

Duplicating a tab preserves the tags of the subject in the original tag, but selected subject is set to Methods

![image](https://github.com/user-attachments/assets/ed0e54c3-6213-4f8e-9db3-b6122564838c)
*duplicating a chem tag gives this*

**Comment by GrimReaper2654** [comment]
grrrr

**Comment by GrimReaper2654** [comment]
I will fix

**Comment by GrimReaper2654** [comment]
fixed
