### ISSUE TITLE
URGENT: Tags are broken

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#72]
![image](https://github.com/user-attachments/assets/64b3dfdd-7576-439e-9842-6f84502fbcda)

Can we revert tag looks? This new look is really bad

Also the tags are not working, can someone revert their commit?

**Comment by RJDJcool3** [comment]
@GrimReaper2654

**Comment by RJDJcool3** [comment]
Never mind, they aren't broken

**Comment by GrimReaper2654** [comment]
all good?
