### ISSUE TITLE
Bold Tags are Ugly

### ISSUE THREAD

**Issue by RJDJcool3** [GrimReaper2654/WACE-Database#73]
![image](https://github.com/user-attachments/assets/f6a74870-0f8f-4395-a74a-ef80994ede50)

Can we revert to the style from before? I don't think the bold tags are a good look.

**Comment by GrimReaper2654** [comment]
nooooo

**Comment by GrimReaper2654** [comment]
aw hail nah

**Comment by GrimReaper2654** [comment]
I'll change it
