### ISSUE TITLE
Add Option to Select Multiple Questions for PDF Creation

### ISSUE THREAD

**Issue by tvdk-sudoku** [GrimReaper2654/WACE-Database#8]
Add a checkbox next to each question so you can select multiple questions to combine together to create a single pdf of those questions.

**Comment by GrimReaper2654** [comment]
I can't figure out a way to do this without having to install dependencies, which I don't want to have. It won't even be an elegant solution as it would put each multi choice questions on a separate page. Probably not going to add this feature in the foreseeable future. Just download the full wace paper instead i guess.

**Comment by GrimReaper2654** [comment]
I ended up doing the anyways lmao
